pipeline {
    agent any
    stages {
      
        stage('Lint HTML') {
            steps {
                sh 'tidy -q -e *.html'
            }
        }
        stage('Build Docker Image') {
            steps {
            }
        }
        stage('Login to Dockerhub') {
            steps {
                withCredentials([string(credentialsId: 'docker-pwd', variable: 'dockerhubpwd')]) {
                }
            }
        }
        stage('Upload Image to Dockerhub') {
            steps {
            }
        }
        stage('Deploy Kubernetes') {
            steps {
            }
        }
    }
}