pipeline {
    agent any
    stages {

        stage('Lint HTML') {
            steps {
                sh 'tidy -q -e index.html'
            }
        }
        stage('Build Docker Image') {
            steps {
                withCredentials([]) {
                    sh '''
                        docker build -t jerrybuild .
                    '''
            }
        }
        stage('Login to Dockerhub') {
            steps {
                withCredentials() {
                    
                }
            }
        }
        stage('Upload Image to Dockerhub') {
            steps {
            }
        }
        stage('Deploy Kubernetes') {
            steps {
            }
        }
    }
}