pipeline {
	agent any
	stages {

		stage('Create cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'AWSCredentials') {
					sh '''
						eksctl create cluster \
						--name capstonejerry \
						--version 1.14 \
						--nodegroup-name workers \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto \
						--region us-east-1 \
						--zones us-east-1a \
						--zones us-east-1b \
						--zones us-east-1c \
					'''
				}
			}
		}

		

		stage('Create kubectl configuration file') {
			steps {
				withAWS(region:'us-east-1', credentials:'AWSCredentials') {
					sh '''
						python -m awscli eks --region us-east-1 update-kubeconfig --name capstonejerry
					'''
				}
			}
		}

	}
}